#!/usr/bin/env node
import { mkdir, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import sharp from "sharp";
import { runBatch, runSingle, warnIfPhotoAssetsRemainLocal, writeRunProof } from "./pipeline.mjs";

function parseArgs(argv) {
  const args = { command: argv[2] ?? "help" };
  for (let i = 3; i < argv.length; i += 1) {
    const arg = argv[i];
    if (!arg.startsWith("--")) continue;
    const key = arg.slice(2);
    const next = argv[i + 1];
    if (!next || next.startsWith("--")) {
      args[key] = true;
    } else {
      args[key] = next;
      i += 1;
    }
  }
  return args;
}

function usage() {
  return `Tripdar catalog-safe photo pipeline

Commands:
  single --input <file> --sku <sku> --product <name> [--mode catalog_safe|premium] [--brand <brand>] [--variant <variant>] [--view front]
  batch --input-dir <dir> --sku <sku> --product <name> [--mode catalog_safe|premium] [--brand <brand>] [--variant <variant>] [--view front]
  make-fixtures --out <dir>

Options:
  --ledger prisma|filesystem   Default: prisma when DATABASE_URL is set, otherwise filesystem.
  --root <dir>                 Blob root directory. Default: tripdar-product-images.
  --mode <mode>                catalog_safe (default) or premium. Premium is always human-gated.
  --format <description>       Product format substituted into the locked premium prompt.
  --operator <name>            Manifest approved_by value for auto-approved jobs.
  --strict-gateway             Route to needs_review when Vercel AI Gateway background removal is unavailable.
  --proof <file>               Write a compact JSON run proof.
`;
}

async function makeFixtures(outDir) {
  await mkdir(outDir, { recursive: true });

  await sharp({
    create: {
      width: 1800,
      height: 2200,
      channels: 4,
      background: "#f7f7f2",
    },
  })
    .composite([
      {
        input: Buffer.from(
          `<svg width="1800" height="2200" xmlns="http://www.w3.org/2000/svg">
            <rect x="585" y="260" width="630" height="1500" rx="92" fill="#ffffff" stroke="#202020" stroke-width="18"/>
            <rect x="642" y="760" width="516" height="560" rx="22" fill="#f6f1d8" stroke="#222" stroke-width="10"/>
            <text x="900" y="910" text-anchor="middle" font-family="Arial" font-size="84" fill="#131313" font-weight="700">NOCTURNAL</text>
            <text x="900" y="1035" text-anchor="middle" font-family="Arial" font-size="76" fill="#1e5c76">BLUE MOON</text>
            <text x="900" y="1160" text-anchor="middle" font-family="Arial" font-size="48" fill="#333">20mg microdose</text>
            <circle cx="1030" cy="535" r="110" fill="#2a7995" opacity="0.9"/>
          </svg>`,
        ),
      },
    ])
    .png()
    .toFile(path.join(outDir, "nocturnal-farms-front.png"));

  await sharp({
    create: {
      width: 900,
      height: 900,
      channels: 4,
      background: "#efefef",
    },
  })
    .composite([
      {
        input: Buffer.from(
          `<svg width="900" height="900" xmlns="http://www.w3.org/2000/svg">
            <rect x="275" y="160" width="350" height="600" rx="62" fill="#111"/>
            <rect x="318" y="430" width="264" height="210" rx="18" fill="#fff"/>
            <text x="450" y="538" text-anchor="middle" font-family="Arial" font-size="42" fill="#111">DARK JAR</text>
          </svg>`,
        ),
      },
    ])
    .png()
    .toFile(path.join(outDir, "dark-jar-review.png"));

  await writeFile(
    path.join(outDir, "README.txt"),
    "Synthetic catalog-safe QA fixtures generated by scripts/photo-pipeline/cli.mjs.\n",
  );
}

async function main() {
  const args = parseArgs(process.argv);
  if (args.command === "help" || args.help) {
    console.log(usage());
    return;
  }

  if (args.command === "make-fixtures") {
    if (!args.out) throw new Error("--out is required");
    await makeFixtures(path.resolve(args.out));
    console.log(`fixtures=${path.resolve(args.out)}`);
    return;
  }

  const common = {
    rootDir: path.resolve(args.root ?? "tripdar-product-images"),
    ledger: args.ledger,
    sku: args.sku,
    brand: args.brand ?? null,
    productName: args.product,
    variant: args.variant ?? null,
    view: args.view ?? "front",
    operator: args.operator ?? "photo-pipeline",
    strictGateway: Boolean(args["strict-gateway"]),
    mode: args.mode ?? "catalog_safe",
    productFormat: args.format ?? null,
  };

  if (!common.sku || !common.productName) {
    throw new Error("--sku and --product are required");
  }

  warnIfPhotoAssetsRemainLocal(common);

  let results;
  if (args.command === "single") {
    if (!args.input) throw new Error("--input is required");
    results = [await runSingle({ ...common, inputPath: path.resolve(args.input) })];
  } else if (args.command === "batch") {
    if (!args["input-dir"]) throw new Error("--input-dir is required");
    const inputDir = path.resolve(args["input-dir"]);
    const entries = await readdir(inputDir);
    const imagePaths = entries
      .filter((entry) => /\.(jpe?g|png|heic|heif|dng|tiff?)$/i.test(entry))
      .map((entry) => path.join(inputDir, entry));
    results = await runBatch({ ...common, inputPaths: imagePaths });
  } else {
    throw new Error(`Unknown command: ${args.command}\n\n${usage()}`);
  }

  if (args.proof) {
    await writeRunProof(path.resolve(args.proof), results);
  }

  for (const result of results) {
    console.log(
      [
        `job=${result.job.jobId}`,
        `status=${result.job.status}`,
        `skipped=${Boolean(result.skipped)}`,
        `quality=${result.job.qualityScore?.toFixed(2) ?? "n/a"}`,
        `manifest=${result.manifestPath}`,
      ].join(" "),
    );
  }
  console.log(`batch_total_cost_cents=${results.reduce((sum, result) => sum + Number(result.job.costCents ?? 0), 0)}`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
